# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVG-Template-Graph
version:      0.13
version_from: lib/SVG/Template/Graph.pm
installdirs:  site
requires:
    Carp:                          0.01
    Config::General:               0
    Data::Dumper:                  2
    POSIX:                         0.01
    SVG:                           2.34
    SVG::Parser:                   1.01
    Transform::Canvas:             0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
